const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',


  //user
  ADD_USER_SUCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

  //admin
  FETCH_ALLCODE_START: 'FETCH_ALLCODE_START',
  FETCH_ALLCODE_SUCCESS: 'FETCH_ALLCODE_SUCCESS',
  FETCH_ALLCODE_FAILED: 'FETCH_ALLCODE_FAILED',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',
  CREATE_USER_START: 'CREATE_USER_START'

})

export default actionTypes;
