const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',


  //user
  ADD_USER_SUCESS: 'ADD_USER_SUCCESS',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //admin
  FETCH_ALLCODE_START: 'FETCH_ALLCODE_START',
  FETCH_ALLCODE_SUCCESS: 'FETCH_ALLCODE_SUCCESS',
  FETCH_ALLCODE_FAILED: 'FETCH_ALLCODE_FAILED',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED: 'CREATE_USER_FAILED',
  CREATE_USER_START: 'CREATE_USER_START',

  FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILED: 'DELETE_USER_FAILED',

  FETCH_USER_BY_ID_START: 'FETCH_USER_BY_ID_START',
  FETCH_USER_BY_ID_SUCCESS: 'FETCH_USER_BY_ID_SUCCESS',
  FETCH_USER_BY_ID_FAILED: 'FETCH_USER_BY_ID_FAILED',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

  FETCH_TOP_DOCTOR_START: 'FETCH_TOP_DOCTOR_START',
  FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
  FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',

  FETCH_ALL_DOCTORS_START: 'FETCH_ALL_DOCTORS_START',
  FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
  FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

  POST_INFO_DOCTOR_START: 'POST_INFO_DOCTOR_START',
  POST_INFO_DOCTOR_SUCCESS: 'POST_INFO_DOCTOR_SUCCESS',
  POST_INFO_DOCTOR_FAILED: 'POST_INFO_DOCTOR_FAILED',

  FETCH_INFO_DOCTOR_START: 'FETCH_INFO_DOCTOR_START',
  FETCH_INFO_DOCTOR_SUCCESS: 'FETCH_INFO_DOCTOR_SUCCESS',
  FETCH_INFO_DOCTOR_FAILED: 'FETCH_INFO_DOCTOR_FAILED',

  POST_SCHEDULE_DOCTOR_START: 'POST_SCHEDULE_DOCTOR_START',
  POST_SCHEDULE_DOCTOR_SUCCESS: 'POST_SCHEDULE_DOCTOR_SUCCESS',
  POST_SCHEDULE_DOCTOR_FAILED: 'POST_SCHEDULE_DOCTOR_FAILED',

  FETCH_SCHEDULE_DOCTOR_START: 'FETCH_SCHEDULE_DOCTOR_START',
  FETCH_SCHEDULE_DOCTOR_SUCCESS: 'FETCH_SCHEDULE_DOCTOR_SUCCESS',
  FETCH_SCHEDULE_DOCTOR_FAILED: 'FETCH_SCHEDULE_DOCTOR_FAILED',

  POST_BOOKING_START: 'POST_BOOKING_START',
  POST_BOOKING_SUCCESS: 'POST_BOOKING_SUCCESS',
  POST_BOOKING_FAILED: 'POST_BOOKING_FAILED',

  POST_NEW_SPECIALTY_START: 'POST_NEW_SPECIALTY_START',
  POST_NEW_SPECIALTY_SUCCESS: 'POST_NEW_SPECIALTY_SUCCESS',
  POST_NEW_SPECIALTY_FAILED: 'POST_NEW_SPECIALTY_FAILED',

  FECTCH_ALL_SPECIALTY_START: 'FECTCH_ALL_SPECIALTY_START',
  FECTCH_ALL_SPECIALTY_SUCCESS: 'FECTCH_ALL_SPECIALTY_SUCCESS',
  FECTCH_ALL_SPECIALTY_FAILED: 'FECTCH_ALL_SPECIALTY_FAILED',

  FETCH_DOCTORS_BY_SPECIALTY_START: 'FETCH_DOCTORS_BY_SPECIALTY_START',
  FETCH_DOCTORS_BY_SPECIALTY_SUCCESS: 'FETCH_DOCTORS_BY_SPECIALTY_SUCCESS',
  FETCH_DOCTORS_BY_SPECIALTY_FAILED: 'FETCH_DOCTORS_BY_SPECIALTY_FAILED',

  POST_NEW_CLINIC_START: 'POST_NEW_CLINIC_START',
  POST_NEW_CLINIC_SUCCESS: 'POST_NEW_CLINIC_SUCCESS',
  POST_NEW_CLINIC_FAILED: 'POST_NEW_CLINIC_FAILED',

  FETCH_ALL_CLINIC_START: 'FETCH_ALL_CLINIC_START',
  FETCH_ALL_CLINIC_SUCCESS: 'FETCH_ALL_CLINIC_SUCCESS',
  FETCH_ALL_CLINIC_FAILED: 'FETCH_ALL_CLINIC_FAILED',

  FETCH_DOCTORS_BY_CLINIC_START: 'FETCH_DOCTORS_BY_CLINIC_START',
  FETCH_DOCTORS_BY_CLINIC_SUCCESS: 'FETCH_DOCTORS_BY_CLINIC_SUCCESS',
  FETCH_DOCTORS_BY_CLINIC_FAILED: 'FETCH_DOCTORS_BY_CLINIC_FAILED'

})

export default actionTypes;
